name: Matrix runs-on

on: push

jobs:
  matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - run: echo "Should run on '${{ matrix.os }}'"
